### ISSUE TITLE
What is the status?

### ISSUE THREAD

**Issue by michaeloa** [JetBrains/teamcity-dashboard-plugin#3]
What's the status on this? One of the big annoyances I have with TC is that there is no way to get an overview of the current status of all the build configs, without setting up external systems. Is this intended to mitigate that issue?

**Comment by Furetur** [comment]
Thanks for reaching out, @michaeloa!

This was an experimental project and it did not achieve its goal.
As a result, this plugin **is very unlikely to work with any of the TeamCity releases**.

However, I think the plugin solves (at least partially) your issue.

Can you please describe your annoyance in detail? I will try to send this feedback to the TeamCity team.

**Comment by michaeloa** [comment]
The annoyance is basically the lack of dashboard functionality. Even a moderately sized enterprise system like the one I'm working with, easily ends up with 50+ projects and 200+ build configurations. Keeping the builds green is of paramount importance, and a good way to keep devs attentive to that is by displaying build status on a monitor in the offices. Teamcity's UI is extremely unsuited to that use-case. The only way to get a good dashboard for TC seems to be to set up another application that uses the TC API (and most of those apps don't appear to be supported).
